version: '3.4'

services:
  catalogdb: 
    image: ${DOCKER_REGISTRY-}mongo

  basketdb: 
    image: ${DOCKER_REGISTRY-}redis:alpine

  discountdb: 
    image: ${DOCKER_REGISTRY-}postgres

  pgadmin: 
    image: ${DOCKER_REGISTRY-}dpage/pgadmin4

  portainer: 
    image: ${DOCKER_REGISTRY-}portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.api/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.Api/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:


